GOLD-450 Added support to create issues from mutations
pinpt/github pull request #25
Opened 2020-10-22 04:08 UTC by josecordaz

2020-10-22 07:54 UTC, pec1985 requested changes

2020-10-22 07:54 UTC, pec1985 commented on internal/mutation.go
>  	logger := sdk.LogWith(g.logger, "customer_id", mutation.CustomerID(), "integration_instance_id", mutation.IntegrationInstanceID())
with recent updates to agent, we need to remove the global `logger` (ie: `g.logger`) and use the one that comes in the function parameter instead, which already contains the customer id and instance id.
```
logger := mutation.Logger
```

2020-10-22 14:46 UTC, Robindiddams commented on internal/mutation.go
>  	logger := sdk.LogWith(g.logger, "customer_id", mutation.CustomerID(), "integration_instance_id", mutation.IntegrationInstanceID())
ditto, and as of v4.0.21 ive included the integration instance id in the logger as well

2020-10-22 18:32 UTC, Robindiddams commented on internal/mutation.go
> +	logger := sdk.LogWith(mutation.Logger())
this is the same as:
```
logger := mutation.Logger()
```

2020-10-22 18:38 UTC, Robindiddams commented on internal/mutation.go
> +	logger := sdk.LogWith(mutation.Logger())
I have the global logger removed in #26  if you wanna help me get that merged then you wont have to address this

2020-10-23 16:09 UTC, Robindiddams approved these changes

2020-10-23 16:13 UTC, merged